version: "3.3"

networks:
  network-app:
  network-proxy:
  bdth-infra-global-network-monitoring:
    external: true

volumes:
  volume-prometheus:
    driver: local
  volume-influxdb:
    driver: local
  volume-grafana:
    driver: local
  volume-alertmanager:
    driver: local
  volume-graphite-conf:
    driver: local
  volume-graphite-stat-storage:
    driver: local
  volume-graphite-functions-dir:
    driver: local
  volume-graphite-nginx-config:
    driver: local
  volume-graphite-statsd-config:
    driver: local
  volume-graphite-logrotate-config:
    driver: local
  volume-graphite-log-files:
    driver: local

configs:
  caddy_config:
    file: ./caddy/Caddyfile
  dockerd_config:
    file: ./dockerd-exporter/Caddyfile
  node_rules:
    file: ./prometheus/rules/swarm_node.rules
  task_rules:
    file: ./prometheus/rules/swarm_task.rules

services:
  proxy:
    image: traefik:v1.4.2
    ports:
      - 82:80
      - 8288:8080
    networks:
      -  network-proxy
    command:
      - --docker
      - --docker.swarmmode
      - --docker.domain=traefik
      - --docker.watch
      - --web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        - "traefik.docker.network=bdth-admin-monitoring_network-proxy"
        - "traefik.port=8080"
        - "traefik.frontend.rule=Host:${ENV_DOMAIN_PREFIX}monitoring-proxy.bdth.hitachivantara.com"
        - "bdth.environment-flip=blue"
        - "bdth.application-name=bdth-admin-monitoring-proxy"
        - "bdth.container-name=bdth-admin-monitoring-proxy"
        - "bdth.domain-name=${ENV_DOMAIN_PREFIX}monitoring-proxy.bdth.hitachivantara.com"

  dockerd-exporter:
    image: stefanprodan/caddy:0.10.10
    networks:
      - network-app
      - network-proxy
    environment:
      - DOCKER_GWBRIDGE_IP=172.18.0.1
    configs:
      - source: dockerd_config
        target: /etc/caddy/Caddyfile
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
      labels:
        - "bdth.environment-flip=blue"
        - "bdth.application-name=bdth-admin-monitoring-dockerd-exporter"
        - "bdth.container-name=bdth-admin-monitoring-dockerd-exporter"

  cadvisor:
    image: google/cadvisor:v0.28.0
    ports:
      - 8281:8080
    networks:
      - network-app
      - network-proxy
    command: -logtostderr -docker_only
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/rootfs:ro
      - /var/run:/var/run
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
      labels:
        - "traefik.docker.network=bdth-admin-monitoring_network-proxy"
        - "traefik.port=8080"
        - "traefik.frontend.rule=Host:${ENV_DOMAIN_PREFIX}cadvisor.bdth.hitachivantara.com"
        - "bdth.environment-flip=blue"
        - "bdth.application-name=bdth-admin-monitoring-cadvisor"
        - "bdth.container-name=bdth-admin-monitoring-cadvisor"
        - "bdth.domain-name=${ENV_DOMAIN_PREFIX}cadvisor.bdth.hitachivantara.com"

  grafana:
    image: joericearchitect/bdth-admin-grafana:1.0.0
    ports:
      - 3000:3000
    networks:
      - network-app
      - network-proxy
      - bdth-infra-global-network-monitoring
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - volume-grafana:/var/lib/grafana
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.bdth.swarm-node-type == admin-monitoring
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
      labels:
        - "traefik.docker.network=bdth-admin-monitoring_network-proxy"
        - "traefik.port=3000"
        - "traefik.frontend.rule=Host:${ENV_DOMAIN_PREFIX}grafana.bdth.hitachivantara.com"
        - "bdth.environment-flip=blue"
        - "bdth.application-name=bdth-infra-grafana"
        - "bdth.container-name=bdth-infra-grafana"
        - "bdth.domain-name=${ENV_DOMAIN_PREFIX}grafana.bdth.hitachivantara.com"

  alertmanager:
    image: stefanprodan/swarmprom-alertmanager
    ports:
      - 9093:9093
    networks:
      - network-app
      - network-proxy
    environment:
      - SLACK_URL=${SLACK_URL:-https://hooks.slack.com/services/TOKEN}
      - SLACK_CHANNEL=${SLACK_CHANNEL:-general}
      - SLACK_USER=${SLACK_USER:-alertmanager}
    command:
      - '-config.file=/etc/alertmanager/alertmanager.yml'
      - '-storage.path=/alertmanager'
    volumes:
      - volume-alertmanager:/alertmanager
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.bdth.swarm-node-type == admin-monitoring
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
      labels:
        - "traefik.docker.network=bdth-admin-monitoring_network-proxy"
        - "traefik.port=9093"
        - "traefik.frontend.rule=Host:${ENV_DOMAIN_PREFIX}alerts.bdth.hitachivantara.com"
        - "bdth.environment-flip=blue"
        - "bdth.application-name=bdth-infra-alertmanager"
        - "bdth.container-name=bdth-infra-alertmanager"
        - "bdth.domain-name=${ENV_DOMAIN_PREFIX}alerts.bdth.hitachivantara.com"

  unsee:
    image: cloudflare/unsee:v0.8.0
    ports:
      - 9094:8080
    networks:
      - network-app
      - network-proxy
    environment:
      - "ALERTMANAGER_URIS=default:http://alertmanager:9093"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.bdth.swarm-node-type == admin-monitoring
      labels:
        - "traefik.docker.network=bdth-admin-monitoring_network-proxy"
        - "traefik.port=8080"
        - "traefik.frontend.rule=Host:${ENV_DOMAIN_PREFIX}unsee.bdth.hitachivantara.com"
        - "bdth.environment-flip=blue"
        - "bdth.application-name=bdth-infra-unsee"
        - "bdth.container-name=bdth-infra-unsee"
        - "bdth.domain-name=${ENV_DOMAIN_PREFIX}unsee.bdth.hitachivantara.com"

  node-exporter:
    image: stefanprodan/swarmprom-node-exporter
    ports:
      - 9100:9100
    networks:
      - network-app
      - network-proxy
    environment:
      - NODE_ID={{.Node.ID}}
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /etc/hostname:/etc/nodename
    command:
      - '-collector.textfile.directory=/etc/node-exporter/'
      - '-collector.procfs=/host/proc'
      - '-collector.sysfs=/host/sys'
      - '-collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
      - '-collectors.enabled=textfile,conntrack,diskstats,entropy,filefd,filesystem,loadavg,mdadm,meminfo,netdev,netstat,stat,time,vmstat'
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
      labels:
        - "bdth.environment-flip=blue"
        - "bdth.application-name=bdth-admin-monitoring-node-exporter"
        - "bdth.container-name=bdth-admin-monitoring-node-exporter"

  graphite-exporter:
    image: joericearchitect/bdth-admin-graphite-exporter:1.0.0
    ports:
      - 9108:9108
      - 8205:9109
    networks:
      - network-app
      - network-proxy
    command:
      - -graphite.mapping-config=/tmp/graphite_mapping.conf
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.bdth.swarm-node-type == admin-monitoring
      resources:
        limits:
          memory: 2048M
        reservations:
          memory: 1024M
      labels:
        - "traefik.docker.network=bdth-admin-monitoring_network-proxy"
        - "traefik.port=9109"
        - "traefik.frontend.rule=Host:${ENV_DOMAIN_PREFIX}graphite.bdth.hitachivantara.com"
        - "bdth.environment-flip=blue"
        - "bdth.application-type=time-database"
        - "bdth.application-sub-type=graphite-exporter"
        - "bdth.application-name=bdth-infra-graphite-exporter"
        - "bdth.container-name=bdth-infra-graphite-exporter"
        
  prometheus:
    image: joericearchitect/bdth-admin-prometheus:1.0.0
    ports:
      - 9090:9090
    networks:
      - network-app
      - network-proxy
      - bdth-infra-global-network-monitoring
    command:
      - '-config.file=/etc/prometheus/prometheus.yml'
      - '-storage.local.path=/prometheus'
      - '-web.console.libraries=/etc/prometheus/console_libraries'
      - '-web.console.templates=/etc/prometheus/consoles'
      - '-storage.local.target-heap-size=1073741824'
      - '-storage.local.retention=24h'
      - '-alertmanager.url=http://alertmanager:9093'
    volumes:
      - volume-prometheus:/prometheus
    configs:
      - source: node_rules
        target: /etc/prometheus/swarm_node.rules
      - source: task_rules
        target: /etc/prometheus/swarm_task.rules
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.bdth.swarm-node-type == admin-monitoring
      resources:
        limits:
          memory: 2048M
        reservations:
          memory: 1024M
      labels:
        - "traefik.docker.network=bdth-admin-monitoring_network-proxy"
        - "traefik.port=9090"
        - "traefik.frontend.rule=Host:${ENV_DOMAIN_PREFIX}prometheus.bdth.hitachivantara.com"
        - "bdth.environment-flip=blue"
        - "bdth.application-type=time-database"
        - "bdth.application-sub-type=prometheus"
        - "bdth.application-name=bdth-infra-prometheus"
        - "bdth.container-name=bdth-infra-prometheus"
        - "bdth.domain-name=${ENV_DOMAIN_PREFIX}prometheus.bdth.hitachivantara.com"

  influxdb:
    image: influxdb:1.4.2
    ports:
      - 8086:8086
    networks:
      - network-app
      - network-proxy
      - bdth-infra-global-network-monitoring
    environment:
      - INFLUXDB_DB=jmeter
      - INFLUXDB_HTTP_AUTH_ENABLED=false
    volumes:
      - volume-influxdb:/var/lib/influxdb
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.bdth.swarm-node-type == admin-monitoring
      resources:
        limits:
          memory: 2048M
        reservations:
          memory: 1024M
      labels:
        - "traefik.docker.network=bdth-admin-monitoring_network-proxy"
        - "traefik.port=8086"
        - "traefik.frontend.rule=Host:${ENV_DOMAIN_PREFIX}influxdb.bdth.hitachivantara.com"
        - "bdth.environment-flip=blue"
        - "bdth.application-type=time-database"
        - "bdth.application-sub-type=influxdb"
        - "bdth.application-name=bdth-infra-influxdb"
        - "bdth.container-name=bdth-infra-influxdb"
        - "bdth.domain-name=${ENV_DOMAIN_PREFIX}influxdb.bdth.hitachivantara.com"

