./transfer-file.sh 3dprinting.meta.stackexchange.com.7z
./transfer-file.sh 3dprinting.stackexchange.com.7z
./transfer-file.sh Sites.xml
./transfer-file.sh academia.meta.stackexchange.com.7z
./transfer-file.sh academia.stackexchange.com.7z
./transfer-file.sh ai.meta.stackexchange.com.7z
./transfer-file.sh ai.stackexchange.com.7z
./transfer-file.sh android.meta.stackexchange.com.7z
./transfer-file.sh android.stackexchange.com.7z
./transfer-file.sh anime.meta.stackexchange.com.7z
./transfer-file.sh anime.stackexchange.com.7z
./transfer-file.sh apple.meta.stackexchange.com.7z
./transfer-file.sh apple.stackexchange.com.7z
./transfer-file.sh arabic.meta.stackexchange.com.7z
./transfer-file.sh arabic.stackexchange.com.7z
./transfer-file.sh arduino.meta.stackexchange.com.7z
./transfer-file.sh arduino.stackexchange.com.7z
./transfer-file.sh askubuntu.com.7z
./transfer-file.sh astronomy.meta.stackexchange.com.7z
./transfer-file.sh astronomy.stackexchange.com.7z
./transfer-file.sh augur.meta.stackexchange.com.7z
./transfer-file.sh augur.stackexchange.com.7z
./transfer-file.sh aviation.meta.stackexchange.com.7z
./transfer-file.sh aviation.stackexchange.com.7z
./transfer-file.sh avp.meta.stackexchange.com.7z
./transfer-file.sh avp.stackexchange.com.7z
./transfer-file.sh beer.meta.stackexchange.com.7z
./transfer-file.sh beer.stackexchange.com.7z
./transfer-file.sh bicycles.meta.stackexchange.com.7z
./transfer-file.sh bicycles.stackexchange.com.7z
./transfer-file.sh bioinformatics.meta.stackexchange.com.7z
./transfer-file.sh bioinformatics.stackexchange.com.7z
./transfer-file.sh biology.meta.stackexchange.com.7z
./transfer-file.sh biology.stackexchange.com.7z
./transfer-file.sh bitcoin.meta.stackexchange.com.7z
./transfer-file.sh bitcoin.stackexchange.com.7z
./transfer-file.sh blender.meta.stackexchange.com.7z
./transfer-file.sh blender.stackexchange.com.7z
./transfer-file.sh boardgames.meta.stackexchange.com.7z
./transfer-file.sh boardgames.stackexchange.com.7z
./transfer-file.sh bricks.meta.stackexchange.com.7z
./transfer-file.sh bricks.stackexchange.com.7z
./transfer-file.sh buddhism.meta.stackexchange.com.7z
./transfer-file.sh buddhism.stackexchange.com.7z
./transfer-file.sh chemistry.meta.stackexchange.com.7z
./transfer-file.sh chemistry.stackexchange.com.7z
./transfer-file.sh chess.meta.stackexchange.com.7z
./transfer-file.sh chess.stackexchange.com.7z
./transfer-file.sh chinese.meta.stackexchange.com.7z
./transfer-file.sh chinese.stackexchange.com.7z
./transfer-file.sh christianity.meta.stackexchange.com.7z
./transfer-file.sh christianity.stackexchange.com.7z
./transfer-file.sh civicrm.meta.stackexchange.com.7z
./transfer-file.sh civicrm.stackexchange.com.7z
./transfer-file.sh codegolf.meta.stackexchange.com.7z
./transfer-file.sh codegolf.stackexchange.com.7z
./transfer-file.sh codereview.meta.stackexchange.com.7z
./transfer-file.sh codereview.stackexchange.com.7z
./transfer-file.sh coffee.meta.stackexchange.com.7z
./transfer-file.sh coffee.stackexchange.com.7z
./transfer-file.sh cogsci.meta.stackexchange.com.7z
./transfer-file.sh cogsci.stackexchange.com.7z
./transfer-file.sh computergraphics.meta.stackexchange.com.7z
./transfer-file.sh computergraphics.stackexchange.com.7z
./transfer-file.sh cooking.meta.stackexchange.com.7z
./transfer-file.sh cooking.stackexchange.com.7z
./transfer-file.sh craftcms.meta.stackexchange.com.7z
./transfer-file.sh craftcms.stackexchange.com.7z
./transfer-file.sh crafts.meta.stackexchange.com.7z
./transfer-file.sh crafts.stackexchange.com.7z
./transfer-file.sh crypto.meta.stackexchange.com.7z
./transfer-file.sh crypto.stackexchange.com.7z
./transfer-file.sh cs.meta.stackexchange.com.7z
./transfer-file.sh cs.stackexchange.com.7z
./transfer-file.sh cseducators.meta.stackexchange.com.7z
./transfer-file.sh cseducators.stackexchange.com.7z
./transfer-file.sh cstheory.meta.stackexchange.com.7z
./transfer-file.sh cstheory.stackexchange.com.7z
./transfer-file.sh datascience.meta.stackexchange.com.7z
./transfer-file.sh datascience.stackexchange.com.7z
./transfer-file.sh dba.meta.stackexchange.com.7z
./transfer-file.sh dba.stackexchange.com.7z
./transfer-file.sh devops.meta.stackexchange.com.7z
./transfer-file.sh devops.stackexchange.com.7z
./transfer-file.sh diy.meta.stackexchange.com.7z
./transfer-file.sh diy.stackexchange.com.7z
./transfer-file.sh drupal.meta.stackexchange.com.7z
./transfer-file.sh drupal.stackexchange.com.7z
./transfer-file.sh dsp.meta.stackexchange.com.7z
./transfer-file.sh dsp.stackexchange.com.7z
./transfer-file.sh earthscience.meta.stackexchange.com.7z
./transfer-file.sh earthscience.stackexchange.com.7z
./transfer-file.sh ebooks.meta.stackexchange.com.7z
./transfer-file.sh ebooks.stackexchange.com.7z
./transfer-file.sh economics.meta.stackexchange.com.7z
./transfer-file.sh economics.stackexchange.com.7z
./transfer-file.sh electronics.meta.stackexchange.com.7z
./transfer-file.sh electronics.stackexchange.com.7z
./transfer-file.sh elementaryos.meta.stackexchange.com.7z
./transfer-file.sh elementaryos.stackexchange.com.7z
./transfer-file.sh ell.meta.stackexchange.com.7z
./transfer-file.sh ell.stackexchange.com.7z
./transfer-file.sh emacs.meta.stackexchange.com.7z
./transfer-file.sh emacs.stackexchange.com.7z
./transfer-file.sh engineering.meta.stackexchange.com.7z
./transfer-file.sh engineering.stackexchange.com.7z
./transfer-file.sh english.meta.stackexchange.com.7z
./transfer-file.sh english.stackexchange.com.7z
./transfer-file.sh es.stackoverflow.com.7z
./transfer-file.sh esperanto.meta.stackexchange.com.7z
./transfer-file.sh esperanto.stackexchange.com.7z
./transfer-file.sh ethereum.meta.stackexchange.com.7z
./transfer-file.sh ethereum.stackexchange.com.7z
./transfer-file.sh expatriates.meta.stackexchange.com.7z
./transfer-file.sh expatriates.stackexchange.com.7z
./transfer-file.sh expressionengine.meta.stackexchange.com.7z
./transfer-file.sh expressionengine.stackexchange.com.7z
./transfer-file.sh fitness.meta.stackexchange.com.7z
./transfer-file.sh fitness.stackexchange.com.7z
./transfer-file.sh freelancing.meta.stackexchange.com.7z
./transfer-file.sh freelancing.stackexchange.com.7z
./transfer-file.sh french.meta.stackexchange.com.7z
./transfer-file.sh french.stackexchange.com.7z
./transfer-file.sh gamedev.meta.stackexchange.com.7z
./transfer-file.sh gamedev.stackexchange.com.7z
./transfer-file.sh gaming.meta.stackexchange.com.7z
./transfer-file.sh gaming.stackexchange.com.7z
./transfer-file.sh gardening.meta.stackexchange.com.7z
./transfer-file.sh gardening.stackexchange.com.7z
./transfer-file.sh genealogy.meta.stackexchange.com.7z
./transfer-file.sh genealogy.stackexchange.com.7z
./transfer-file.sh german.meta.stackexchange.com.7z
./transfer-file.sh german.stackexchange.com.7z
./transfer-file.sh gis.meta.stackexchange.com.7z
./transfer-file.sh gis.stackexchange.com.7z
./transfer-file.sh graphicdesign.meta.stackexchange.com.7z
./transfer-file.sh graphicdesign.stackexchange.com.7z
./transfer-file.sh ham.meta.stackexchange.com.7z
./transfer-file.sh ham.stackexchange.com.7z
./transfer-file.sh hardwarerecs.meta.stackexchange.com.7z
./transfer-file.sh hardwarerecs.stackexchange.com.7z
./transfer-file.sh health.meta.stackexchange.com.7z
./transfer-file.sh health.stackexchange.com.7z
./transfer-file.sh hermeneutics.meta.stackexchange.com.7z
./transfer-file.sh hermeneutics.stackexchange.com.7z
./transfer-file.sh hinduism.meta.stackexchange.com.7z
./transfer-file.sh hinduism.stackexchange.com.7z
./transfer-file.sh history.meta.stackexchange.com.7z
./transfer-file.sh history.stackexchange.com.7z
./transfer-file.sh homebrew.meta.stackexchange.com.7z
./transfer-file.sh homebrew.stackexchange.com.7z
./transfer-file.sh hsm.meta.stackexchange.com.7z
./transfer-file.sh hsm.stackexchange.com.7z
./transfer-file.sh interpersonal.meta.stackexchange.com.7z
./transfer-file.sh interpersonal.stackexchange.com.7z
./transfer-file.sh iot.meta.stackexchange.com.7z
./transfer-file.sh iot.stackexchange.com.7z
./transfer-file.sh islam.meta.stackexchange.com.7z
./transfer-file.sh islam.stackexchange.com.7z
./transfer-file.sh italian.meta.stackexchange.com.7z
./transfer-file.sh italian.stackexchange.com.7z
./transfer-file.sh ja.stackoverflow.com.7z
./transfer-file.sh japanese.meta.stackexchange.com.7z
./transfer-file.sh japanese.stackexchange.com.7z
./transfer-file.sh joomla.meta.stackexchange.com.7z
./transfer-file.sh joomla.stackexchange.com.7z
./transfer-file.sh judaism.meta.stackexchange.com.7z
./transfer-file.sh judaism.stackexchange.com.7z
./transfer-file.sh korean.meta.stackexchange.com.7z
./transfer-file.sh korean.stackexchange.com.7z
./transfer-file.sh languagelearning.meta.stackexchange.com.7z
./transfer-file.sh languagelearning.stackexchange.com.7z
./transfer-file.sh latin.meta.stackexchange.com.7z
./transfer-file.sh latin.stackexchange.com.7z
./transfer-file.sh law.meta.stackexchange.com.7z
./transfer-file.sh law.stackexchange.com.7z
./transfer-file.sh license.txt
./transfer-file.sh lifehacks.meta.stackexchange.com.7z
./transfer-file.sh lifehacks.stackexchange.com.7z
./transfer-file.sh linguistics.meta.stackexchange.com.7z
./transfer-file.sh linguistics.stackexchange.com.7z
./transfer-file.sh literature.meta.stackexchange.com.7z
./transfer-file.sh literature.stackexchange.com.7z
./transfer-file.sh magento.meta.stackexchange.com.7z
./transfer-file.sh magento.stackexchange.com.7z
./transfer-file.sh martialarts.meta.stackexchange.com.7z
./transfer-file.sh martialarts.stackexchange.com.7z
./transfer-file.sh math.meta.stackexchange.com.7z
./transfer-file.sh math.stackexchange.com.7z
./transfer-file.sh matheducators.meta.stackexchange.com.7z
./transfer-file.sh matheducators.stackexchange.com.7z
./transfer-file.sh mathematica.meta.stackexchange.com.7z
./transfer-file.sh mathematica.stackexchange.com.7z
./transfer-file.sh mathoverflow.net.7z
./transfer-file.sh mechanics.meta.stackexchange.com.7z
./transfer-file.sh mechanics.stackexchange.com.7z
./transfer-file.sh meta.askubuntu.com.7z
./transfer-file.sh meta.es.stackoverflow.com.7z
./transfer-file.sh meta.ja.stackoverflow.com.7z
./transfer-file.sh meta.mathoverflow.net.7z
./transfer-file.sh meta.pt.stackoverflow.com.7z
./transfer-file.sh meta.ru.stackoverflow.com.7z
./transfer-file.sh meta.serverfault.com.7z
./transfer-file.sh meta.stackexchange.com.7z
./transfer-file.sh meta.stackoverflow.com.7z
./transfer-file.sh meta.superuser.com.7z
./transfer-file.sh meta.ukrainian.stackexchange.com.7z
./transfer-file.sh meta.vegetarianism.stackexchange.com.7z
./transfer-file.sh moderators.meta.stackexchange.com.7z
./transfer-file.sh moderators.stackexchange.com.7z
./transfer-file.sh monero.meta.stackexchange.com.7z
./transfer-file.sh monero.stackexchange.com.7z
./transfer-file.sh money.meta.stackexchange.com.7z
./transfer-file.sh money.stackexchange.com.7z
./transfer-file.sh movies.meta.stackexchange.com.7z
./transfer-file.sh movies.stackexchange.com.7z
./transfer-file.sh music.meta.stackexchange.com.7z
./transfer-file.sh music.stackexchange.com.7z
./transfer-file.sh musicfans.meta.stackexchange.com.7z
./transfer-file.sh musicfans.stackexchange.com.7z
./transfer-file.sh mythology.meta.stackexchange.com.7z
./transfer-file.sh mythology.stackexchange.com.7z
./transfer-file.sh networkengineering.meta.stackexchange.com.7z
./transfer-file.sh networkengineering.stackexchange.com.7z
./transfer-file.sh opendata.meta.stackexchange.com.7z
./transfer-file.sh opendata.stackexchange.com.7z
./transfer-file.sh opensource.meta.stackexchange.com.7z
./transfer-file.sh opensource.stackexchange.com.7z
./transfer-file.sh outdoors.meta.stackexchange.com.7z
./transfer-file.sh outdoors.stackexchange.com.7z
./transfer-file.sh parenting.meta.stackexchange.com.7z
./transfer-file.sh parenting.stackexchange.com.7z
./transfer-file.sh patents.meta.stackexchange.com.7z
./transfer-file.sh patents.stackexchange.com.7z
./transfer-file.sh pets.meta.stackexchange.com.7z
./transfer-file.sh pets.stackexchange.com.7z
./transfer-file.sh philosophy.meta.stackexchange.com.7z
./transfer-file.sh philosophy.stackexchange.com.7z
./transfer-file.sh photo.meta.stackexchange.com.7z
./transfer-file.sh photo.stackexchange.com.7z
./transfer-file.sh physics.meta.stackexchange.com.7z
./transfer-file.sh physics.stackexchange.com.7z
./transfer-file.sh pm.meta.stackexchange.com.7z
./transfer-file.sh pm.stackexchange.com.7z
./transfer-file.sh poker.meta.stackexchange.com.7z
./transfer-file.sh poker.stackexchange.com.7z
./transfer-file.sh politics.meta.stackexchange.com.7z
./transfer-file.sh politics.stackexchange.com.7z
./transfer-file.sh portuguese.meta.stackexchange.com.7z
./transfer-file.sh portuguese.stackexchange.com.7z
./transfer-file.sh productivity.meta.stackexchange.com.7z
./transfer-file.sh productivity.stackexchange.com.7z
./transfer-file.sh pt.stackoverflow.com.7z
./transfer-file.sh puzzling.meta.stackexchange.com.7z
./transfer-file.sh puzzling.stackexchange.com.7z
./transfer-file.sh quant.meta.stackexchange.com.7z
./transfer-file.sh quant.stackexchange.com.7z
./transfer-file.sh raspberrypi.meta.stackexchange.com.7z
./transfer-file.sh raspberrypi.stackexchange.com.7z
./transfer-file.sh readme.txt
./transfer-file.sh retrocomputing.meta.stackexchange.com.7z
./transfer-file.sh retrocomputing.stackexchange.com.7z
./transfer-file.sh reverseengineering.meta.stackexchange.com.7z
./transfer-file.sh reverseengineering.stackexchange.com.7z
./transfer-file.sh robotics.meta.stackexchange.com.7z
./transfer-file.sh robotics.stackexchange.com.7z
./transfer-file.sh rpg.meta.stackexchange.com.7z
./transfer-file.sh rpg.stackexchange.com.7z
./transfer-file.sh ru.stackoverflow.com.7z
./transfer-file.sh rus.meta.stackexchange.com.7z
./transfer-file.sh rus.stackexchange.com.7z
./transfer-file.sh russian.meta.stackexchange.com.7z
./transfer-file.sh russian.stackexchange.com.7z
./transfer-file.sh salesforce.meta.stackexchange.com.7z
./transfer-file.sh salesforce.stackexchange.com.7z
./transfer-file.sh scicomp.meta.stackexchange.com.7z
./transfer-file.sh scicomp.stackexchange.com.7z
./transfer-file.sh scifi.meta.stackexchange.com.7z
./transfer-file.sh scifi.stackexchange.com.7z
./transfer-file.sh security.meta.stackexchange.com.7z
./transfer-file.sh security.stackexchange.com.7z
./transfer-file.sh serverfault.com.7z
./transfer-file.sh sharepoint.meta.stackexchange.com.7z
./transfer-file.sh sharepoint.stackexchange.com.7z
./transfer-file.sh sitecore.meta.stackexchange.com.7z
./transfer-file.sh sitecore.stackexchange.com.7z
./transfer-file.sh skeptics.meta.stackexchange.com.7z
./transfer-file.sh skeptics.stackexchange.com.7z
./transfer-file.sh softwareengineering.meta.stackexchange.com.7z
./transfer-file.sh softwareengineering.stackexchange.com.7z
./transfer-file.sh softwarerecs.meta.stackexchange.com.7z
./transfer-file.sh softwarerecs.stackexchange.com.7z
./transfer-file.sh sound.meta.stackexchange.com.7z
./transfer-file.sh sound.stackexchange.com.7z
./transfer-file.sh space.meta.stackexchange.com.7z
./transfer-file.sh space.stackexchange.com.7z
./transfer-file.sh spanish.meta.stackexchange.com.7z
./transfer-file.sh spanish.stackexchange.com.7z
./transfer-file.sh sports.meta.stackexchange.com.7z
./transfer-file.sh sports.stackexchange.com.7z
./transfer-file.sh sqa.meta.stackexchange.com.7z
./transfer-file.sh sqa.stackexchange.com.7z
./transfer-file.sh stackapps.com.7z
./transfer-file.sh stackexchange_archive.torrent
./transfer-file.sh stackexchange_files.xml
./transfer-file.sh stackexchange_meta.sqlite
./transfer-file.sh stackexchange_meta.xml
./transfer-file.sh stackexchange_reviews.xml
./transfer-file.sh stackoverflow.com-Badges.7z
./transfer-file.sh stackoverflow.com-Comments.7z
./transfer-file.sh stackoverflow.com-PostHistory.7z
./transfer-file.sh stackoverflow.com-PostLinks.7z
./transfer-file.sh stackoverflow.com-Posts.7z
./transfer-file.sh stackoverflow.com-Tags.7z
./transfer-file.sh stackoverflow.com-Users.7z
./transfer-file.sh stackoverflow.com-Votes.7z
./transfer-file.sh startups.meta.stackexchange.com.7z
./transfer-file.sh startups.stackexchange.com.7z
./transfer-file.sh stats.meta.stackexchange.com.7z
./transfer-file.sh stats.stackexchange.com.7z
./transfer-file.sh superuser.com.7z
./transfer-file.sh sustainability.meta.stackexchange.com.7z
./transfer-file.sh sustainability.stackexchange.com.7z
./transfer-file.sh tex.meta.stackexchange.com.7z
./transfer-file.sh tex.stackexchange.com.7z
./transfer-file.sh tor.meta.stackexchange.com.7z
./transfer-file.sh tor.stackexchange.com.7z
./transfer-file.sh travel.meta.stackexchange.com.7z
./transfer-file.sh travel.stackexchange.com.7z
./transfer-file.sh tridion.meta.stackexchange.com.7z
./transfer-file.sh tridion.stackexchange.com.7z
./transfer-file.sh ukrainian.stackexchange.com.7z
./transfer-file.sh unix.meta.stackexchange.com.7z
./transfer-file.sh unix.stackexchange.com.7z
./transfer-file.sh ux.meta.stackexchange.com.7z
./transfer-file.sh ux.stackexchange.com.7z
./transfer-file.sh vegetarianism.stackexchange.com.7z
./transfer-file.sh vi.meta.stackexchange.com.7z
./transfer-file.sh vi.stackexchange.com.7z
./transfer-file.sh webapps.meta.stackexchange.com.7z
./transfer-file.sh webapps.stackexchange.com.7z
./transfer-file.sh webmasters.meta.stackexchange.com.7z
./transfer-file.sh webmasters.stackexchange.com.7z
./transfer-file.sh windowsphone.meta.stackexchange.com.7z
./transfer-file.sh windowsphone.stackexchange.com.7z
./transfer-file.sh woodworking.meta.stackexchange.com.7z
./transfer-file.sh woodworking.stackexchange.com.7z
./transfer-file.sh wordpress.meta.stackexchange.com.7z
./transfer-file.sh wordpress.stackexchange.com.7z
./transfer-file.sh workplace.meta.stackexchange.com.7z
./transfer-file.sh workplace.stackexchange.com.7z
./transfer-file.sh worldbuilding.meta.stackexchange.com.7z
./transfer-file.sh worldbuilding.stackexchange.com.7z
./transfer-file.sh writers.meta.stackexchange.com.7z
./transfer-file.sh writers.stackexchange.com.7z